# Generated by Django 4.2.13 on 2024-06-03 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeType',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=15)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('deanId', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='PROGRAMAS',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nam', models.CharField(max_length=40)),
                ('areaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.area')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('cityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.city')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40)),
                ('birthPlace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.city')),
                ('contractType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.contracttype')),
                ('employeeType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.employeetype')),
                ('facultyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.faculty')),
                ('locationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.location')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('countryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.country')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='dptId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.department'),
        ),
        migrations.AddField(
            model_name='area',
            name='coordinatorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.employee'),
        ),
        migrations.AddField(
            model_name='area',
            name='facultyId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.faculty'),
        ),
    ]
