# Generated by Django 5.1.3 on 2024-11-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_equipment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='battery_life',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='processor',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='resolution',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='screen_size',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='storage',
        ),
        migrations.AddField(
            model_name='equipment',
            name='mongo_document_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
